# -*- coding: utf-8 -*-
"""web3txlog

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tvf8vj_erpVzFAXgLJIz7q58CYt0YDNa
@Minh
"""

import argparse
import os
from web3 import Web3
from eth_utils import to_wei, encode_hex
import time
def prepare_web3 (rpc_url = "https://eth-mainnet.public.blastapi.io/"):
  w3 = Web3(Web3.HTTPProvider(rpc_url))
  block = w3.eth.get_block('latest')
  print ("Connected, latest block ", block.number)
  return w3

#A normal transaction with 9 log entries (decoded): 
#https://etherscan.io/tx/0x2272f93e8ce2b475521ed436cd72fca150fd6b672a867b9e6971b8c0dea5c331#eventlog
#An exploit transaction made by hacker with 164 log entries: 	
#https://etherscan.io/tx/0x0fe2542079644e107cbf13690eb9c2c65963ccb79089ff96bfaf8dced2331c92#eventlog
#Another exploit transaction with 34 log entries https://etherscan.io/tx/0xb25e3f872896a0fde22ce60b57553b5304aa4584c47bdb293589bdbd3317de65#eventlog


# log entry has address 
# return all addresses own log entry + classify these addresses
# TODO: inside log topics also has address, detect & decode these. 
def process_tx(w3,tx_hash):
  addresses = []
  logs = w3.eth.getTransactionReceipt(tx_hash).logs
  #using public RPC must restrict the connection number
  time.sleep(0.1)
  for log in logs:
    if(log['address']):
      addresses.append(log['address'])
  return addresses
# TODO: input: ETH address, output: which class that address belong to 
# (e.g. currently : 
# + DEX (e.g. uniswap)
# + flashloan provider (e.g. Aave)
# + Token contract (specify which type):
#     + Stable Coin (Dont need to classify stable coin to erc20)
#     + ERC 721
#     + ERC 20
#     + ERC 1155
#     + Nonstandard tokens
# + What else that we can think of ?...
# + other contracts (e.g. contracts with bytecode & we cant understand)
# + normal address
def classify_address(w3, addresses):
  ...

# get all tx hashes from_block, to_block, will be used as input to process_tx
def get_tx_list(w3, from_block, to_block):
  tx_list = []
  for i in range(from_block, to_block):
    block = w3.eth.get_block(i)
    tx_list.extend(list(map(lambda x: Web3.toHex(x),block.transactions)))
  return tx_list


# print(get_tx_list(w3, 15005468, 15005470))
# target_tx_hash = "0x2272f93e8ce2b475521ed436cd72fca150fd6b672a867b9e6971b8c0dea5c331"
# print(process_tx(w3,target_tx_hash))
if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("-t", "--transaction", type=str, help="transaction hash to analyze")
    parser.add_argument( "--start-block", type=int, help="Start block number to analyze")
    parser.add_argument( "--num-block", type=int, default=1 , help="number of blocks to analyze")
    args = parser.parse_args()
    w3 = prepare_web3()
    if args.transaction:
        addr_list = process_tx(w3, args.transaction)
        print ("list of log addr ", addr_list)
        exit(0)
    if args.start_block:
        tx_list = get_tx_list(w3, args.start_block, args.start_block + args.num_block)
        addr_list = []
        for tx in tx_list:
          addr_list.append(process_tx(w3, tx))
        print ("list of log addr ", addr_list)