# Function to collect transaction traces and save them as JSON files
import json
import os
import subprocess

cast_bin = os.environ.get('CAST_BIN', 'cast')


def cast_run(rpc_url, txhash, raw, output):
    print('Foundry Start')
    # Define the command
    command = [
        'cast', 'run', txhash,
        '-r', rpc_url, '--decode-internal', '--with-state-changes', '-j'
    ]

    # Run the command and capture the output
    result = subprocess.run(command, capture_output=True, text=True, check=True)

    lines = result.stdout.strip().split('\n')
    traces_index = -1

    for index, line in enumerate(lines):
        if 'Traces:' in line:
            traces_index = index
            break
    output_lines = lines[traces_index + 1:]

    filtered_output = '\n'.join(output_lines)  # Join the remaining lines
    json_output = json.loads(filtered_output)

    # Write the filtered output to a file
    # with open(raw, 'w') as raw_file:
    #   json.dump(json_output, raw_file, indent = 2)

    formal_result = original_json(json_output['arena'])

    # Write the filtered output to a file
    with open(output, 'w') as json_file:
        json.dump(formal_result, json_file, indent=2)

    # Return the loaded JSON from the filtered output
    print('Foundry End')

    return formal_result


def collect_trace(transaction_hash, edpool, folder_prefix="result"):
    # Create a directory if it doesn't exist
    raw_directory = folder_prefix + '/raw_json'
    # os.makedirs(raw_directory, exist_ok=True)
    output_directory = folder_prefix + '/trace_json'
    os.makedirs(output_directory, exist_ok=True)
    raw_filename = os.path.join(raw_directory, f"raw_{transaction_hash}.json")
    filename = os.path.join(output_directory, f"trace_{transaction_hash}.json")
    rpc = edpool.endpoint_by_chain()
    while True:
        try:
            # Initialize Web3 instance with the RPC provider
            cast_run(rpc, transaction_hash, raw_filename, filename)
            break
        except subprocess.CalledProcessError as e:
            rpc = edpool.mark_endpoint_broken(rpc)
            print(f'Error processing request: {e}\n retry ... ')
            # Handle the CalledProcessError

        except Exception as e:
            raise RuntimeError(f"An unexpected error occurred: {e}")
            # Handle other unexpected exceptions

        print('trace_finished', transaction_hash)


# Used to Transform New Version of Foundry Output to Clear Json
def original_json(dictlist):
    # Collect the new calls
    new_element_dict = {}
    # Use a stack to store event logs
    ahead_log_dict = {}

    after_log_dict = {}

    for element in dictlist:
        # Get the location of the call
        idx = element["idx"]
        father = element['parent']
        children = element['children']
        depth = element['trace']['depth']
        new_trace = element['trace']

        if element['trace']['kind'].lower() == 'delegatecall':
            # Remove keys in father_call that are greater than the current depth
            event_address = new_element_dict[father][2]

        else:
            event_address = new_trace['address'].lower()

        # If the call has event logs
        if len(element['logs']) != 0:
            # Assume that the sequence of the logs is not reversed
            # Since the events of inner calls generated by this call will be popped first
            # The log stack should be LIFO and the sequence of the logs need to be reversed
            for log in element['logs']:
                log_position = log['position']
                newlog = {
                    'from': event_address,
                    'kind': 'event',
                    'decoded': log['decoded'],
                    'raw': log['raw_log'],
                    'depth': depth
                }
                if len(children) == 0:
                    log_idx = idx + 1
                elif len(children) == log['position']:
                    log_idx = -1
                else:
                    log_idx = children[log_position]

                if log_idx >= 0:
                    if log_idx not in ahead_log_dict:
                        ahead_log_dict[log_idx] = [newlog]
                    else:
                        ahead_log_dict[log_idx].append(newlog)
                else:
                    if children[-1] not in after_log_dict:
                        after_log_dict[children[-1]] = [[newlog, depth]]
                    else:
                        after_log_dict[children[-1]].append([newlog, depth])

        # Collect the new call
        new_call = {
            'from': new_trace['caller'].lower(),
            'to': new_trace['address'].lower(),
            'depth': depth,
            'kind': new_trace['kind'].lower(),
            'success': new_trace['success'],
            'gas_used': new_trace['gas_used'],
            'value': new_trace['value'],
            'data': new_trace['data'],
            'output': new_trace['output'],
            # Get all state changes in steps
            'statechanges': collect_state_changes(new_trace['steps']),
            'status': new_trace['status'],
            'decoded': new_trace['decoded'],
        }

        new_element_dict[idx] = [new_call, father, event_address, children, depth]

    # Add the call to the list by idx
    new_element_list = []

    for key in new_element_dict:
        if key in ahead_log_dict:
            for nlog in ahead_log_dict[key]:
                new_element_list.append(nlog)
            del ahead_log_dict[key]

        for akey in after_log_dict:
            if akey < key:
                for levent in after_log_dict[akey]:
                    if levent[1] >= new_element_dict[key][4]:
                        new_element_list.append(levent[0])
                        after_log_dict[akey].remove(levent)

        new_element_list.append(new_element_dict[key][0])

    for key in ahead_log_dict:
        for nlog in ahead_log_dict[key]:
            new_element_list.append(nlog)

    sorted_afters = sorted(after_log_dict.keys(), reverse=True)

    for key in sorted_afters:
        for levent in after_log_dict[key]:
            new_element_list.append(levent[0])

    return new_element_list


# Collect all state changes in the steps of a call trace
def collect_state_changes(steps):
    state_changes_list = []
    for step in steps:
        # If a step hs storage change
        if step['storage_change']:
            state_changes_list.append(step['storage_change'])
    return state_changes_list
